spring:
  application:
    name: "UserDiary"
  profiles:
    active: dev #set profile here
  sleuth:
    traceId128: true
    sampler:
      percentage: 1.0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.web: ERROR
    com.practice.spring: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
  path: "logs"
  file: "${logging.path}/log.log"
  pattern:
    level: "%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

---
# Defining dev profile
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "postgres"
    url: jdbc:postgresql://localhost:5432/pusers
server:
  port: 8080
security:
  ignored: /**

---
# Defining production profile
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "postgres"
    url: jdbc:postgresql://localhost:5432/pusers
server:
  port: 8181

---
# Defining test profile
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
    path: /h2-console

